### ISSUE TITLE
No reaction within Apple HomeKit

### ISSUE THREAD

**Issue by r-kaandorp** [F4stFr3ddy/homebridge-jablotron-alarm#3]
Hi there, 

I've a running Homebridge installed on my raspberry pi, I was happy to find out that you've written a plugin to work with the MyJablotron alarm system.

Unfortunately something is not working properly, the plugin is installed correctly, no issues there. I've used your commands to retrieve the session id etc. But when I alter the config file and reboot the Homebridge something goes wrong. I still see my Homebridge within the Home app as well as the 'new' alarm button, but both are giving no reaction. (also other devices connected trough Homebridge stopped working). 

Please advice.

**Comment by F4stFr3ddy** [comment]
Hi!

What device are you using for both the Homebridge and Jablotron?

If other devices stopped working it sounds like a Homebridge issue. Usually what happens if the Jablotron config is wrong, the Alarm will either not respond at all, or just do nothing.

Let me know, we could set up a call to solve it.

Best,

Freddy

**Comment by F4stFr3ddy** [comment]
Please try the latest version, it is now native node and should work better and faster. Hopefully it solves your issue, please report back.

**Comment by r-kaandorp** [comment]
Thanks for your reply, sorry for my late response.

I'm using the jablotron 100, and a raspberry pi running homebridge in a docker environment.

I will try using the latest version and will report back. 

Thanks in advance.
