### ISSUE TITLE
[IDEA] Config to select which States will appear

### ISSUE THREAD

**Issue by tampiss** [F4stFr3ddy/homebridge-jablotron-alarm#56]
Hello, 
first thank you for such a great plugin - love it!

I was wondering if it would be possible to enable config per Section in terms of States passed from Homebridge to Homekit. Currently Homekit has 4 states, yet for my purpose only two are really used (Off as disarmed and Away as armed). I saw in other Alarm plugins for HB there was an ability to select which states are sent/visible in Homekit.

Do you think anything such this would be possible to add into the config per Sections in a future?

Best, Martin

== 

PS: actually even for my purpose the matching Satest between HB and Homekit would be even better. I mean if it would be possible to lets say:

- display only two stats in Homekit 
- one as **Home** -> which would match with **disarmed**
- one for **Away** -> which would match with **armed**

**This would be easier for my understanding of what's happening within set stats :-D**

**Comment by F4stFr3ddy** [comment]
Hi,

Thank you very much for your enthusiasm!

Back when this plugin was developed this was not an option, can you refer to other plugins that use this? I can and will implement it as its also something that I would appreciate 😄 

Best regards,

Freddy

**Comment by tampiss** [comment]
Hi, sure. 

This is the plugin https://github.com/MiguelRipoll23/homebridge-securitysystem#readme. Below are two print screens from HK app. Within the HB plugin -> Advance section -> you can check which States are disabled in HK.. Tried two options...

- display only home/away
- display 3 states home/away/off

![IMG_4295](https://user-images.githubusercontent.com/433677/111635919-48537400-87f8-11eb-8b4a-d08254221305.PNG)
![IMG_4294](https://user-images.githubusercontent.com/433677/111635931-4ab5ce00-87f8-11eb-931f-b00644635b90.PNG)

**Comment by tampiss** [comment]
Hi Freddy,
Id have one more idea of how to possibly combine two sections in one. 

I have section Home which arms two floors (two sections downstairs and upstairs) and then I use section Downstairs to arm downstairs floor over the night. 

Such combination would lead to case of having only one section in HK with states:

Home = JA Home section disarmed
Away = JA Home section armed
Night = JA Downstairs section armed

I believe it would be more difficult to program, but that would be great for my case. 

Either way, even disabling some states will be an asset. 

Thank you, M

**Comment by misncz** [comment]
@tampiss you can't get rid of Off as it's the only disarmed state for Homekit. In plugin itself you can disable it but in that case it stops working in Homekit because it lost its the only disarmed state. I modified the plugin code so that it:

- allows to remap armed state to one of Home/Away/Night
- allows to remap partially armed state to one of Home/Away/Night
- automatically sets available target states based on the config so it can be one of:
        - disarmed + armed ... eg Off / Home
        - disarmed + partially armed + armed ... eg Off / Night / Away. This is valid if partial armed is enabled (based on keyboard_key section config option and Jablotron unit config). This is what we have for House section at home - single click on Jablotron unit section's arm button arms the whole house including motion sensors, double click on Jablotron unit section's arm button arms the "perimeter" only (without motion sensors - this is what we use for nights)

I'm going to send pull request to @F4stFr3ddy for this change. As for your other request - to combine 2 Jablotron sections into single Homekit security system. It honestly doesn't make sense to me. It basically is what I described above for our home setup and partial armed state at nights. I'd suggest to get rid of Downstairs section and ask Jablotron guy to reconfigure Home section the same way we have it (single vs double click on arm button)

Last but not least - pics from modified plugin after the change applied based on your request - thanks for it!

![IMG_3848](https://user-images.githubusercontent.com/3840161/113363355-f01c8600-9350-11eb-8cfc-ae95b0048958.jpeg)
![IMG_3849](https://user-images.githubusercontent.com/3840161/113363364-f7439400-9350-11eb-9dca-a693fb95b5b8.jpeg)

**Comment by tampiss** [comment]
@misncz great 👏 thank you. Regarding my current set up, I will speak to the Jablotron guy and will see. Thank you. M

**Comment by tampiss** [comment]
@misncz, @F4stFr3ddy  so I had the service guy here to reconfigure my alarm system. All is as I need and works like a charm.. Thank you. 

One thing to consider: I use NodeRed and the HB plugin for Jablotron returns Current and Target state, which is great.. Due to fact I now have 3 states within one section and I would like to mainly focus on Night mode (as there might be some good automatizations) it would be super great if the response would also return some info regarding "what/how" the state achieved the target state. I mean, if I do full arm then 1, if I do partial arm then 2... Or anyhow differently...

What I am trying to achieve:
- through NodeRed I create Homekit contact sensor (which I use for info regarding armed/disarmed state of night mode)
- if target state = 2 (night) I can set the contact sensor to its needed position
- if target state = 3 (disarmed) I can surely set the opposite, but unfortunately if this happens with the whole house, this changes the position as well and then it does not make sense - if you know what I mean

Thank you, Martin

**Comment by F4stFr3ddy** [comment]
Great to hear, enjoy!
